version: 2

jobs:
  build:
    working_directory: ~/OKTools
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - run: mvn clean install test

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
