version: 2

jobs:
  build:
    working_directory: ~/OKTools
    docker:
    - image: circleci/openjdk:8u181-jdk
    steps:
      - checkout
      - run: mvn clean package
      - store_artifacts:
        path: artifacts
        destination: build
      - store_test_results:
        path: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
