version: 2
jobs:
  build:
    working_directory: ~/OKTools
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - restore_cache:
        key: OKTools-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline # gets the project dependencies
    - save_cache: # saves the project dependencies
        paths:
          - ~/.m2
        key: OKTools-{{ checksum "pom.xml" }}
    - run: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
