/**
 * Autogenerated by Thrift Compiler (0.13.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.github.okzhu.tools.thrift.api.service.invoke;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * 劲量不要用这个方法来条用远程的方法
 * 这个是直接内部反射 内部类。这样就跳过了权限校验。非常不安全
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-06-16")
public class ThriftInvokeRequest implements org.apache.thrift.TBase<ThriftInvokeRequest, ThriftInvokeRequest._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftInvokeRequest> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftInvokeRequest");

    private static final org.apache.thrift.protocol.TField HEADERS_FIELD_DESC = new org.apache.thrift.protocol.TField("headers", org.apache.thrift.protocol.TType.MAP, (short) 1);
    private static final org.apache.thrift.protocol.TField CONTROLLER_FIELD_DESC = new org.apache.thrift.protocol.TField("controller", org.apache.thrift.protocol.TType.STRING, (short) 2);
    private static final org.apache.thrift.protocol.TField METHOD_FIELD_DESC = new org.apache.thrift.protocol.TField("method", org.apache.thrift.protocol.TType.STRING, (short) 3);
    private static final org.apache.thrift.protocol.TField DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("data", org.apache.thrift.protocol.TType.STRING, (short) 4);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftInvokeRequestStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftInvokeRequestTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable
    java.util.Map<java.lang.String, java.lang.String> headers; // required
    /**
     * controller 就是java的类 注意这个 我们项目中间 controller 是需要取一个别名的
     */
    public @org.apache.thrift.annotation.Nullable
    java.lang.String controller; // optional
    public @org.apache.thrift.annotation.Nullable
    java.lang.String method; // optional
    /**
     * data 注意这个地方 为了兼容多个参数。传递的是一个 json的数组
     * 全部都是数组 哪怕你调用的method 只有一个对象 也用数组包裹一下  Arrays.asList
     */
    public @org.apache.thrift.annotation.Nullable
    java.lang.String data; // optional

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        HEADERS((short) 1, "headers"),
        /**
         * controller 就是java的类 注意这个 我们项目中间 controller 是需要取一个别名的
         */
        CONTROLLER((short) 2, "controller"),
        METHOD((short) 3, "method"),
        /**
         * data 注意这个地方 为了兼容多个参数。传递的是一个 json的数组
         * 全部都是数组 哪怕你调用的method 只有一个对象 也用数组包裹一下  Arrays.asList
         */
        DATA((short) 4, "data");

        private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
                case 1: // HEADERS
                    return HEADERS;
                case 2: // CONTROLLER
                    return CONTROLLER;
                case 3: // METHOD
                    return METHOD;
                case 4: // DATA
                    return DATA;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(java.lang.String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final java.lang.String _fieldName;

        _Fields(short thriftId, java.lang.String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        public short getThriftFieldId() {
            return _thriftId;
        }

        public java.lang.String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final _Fields optionals[] = {_Fields.CONTROLLER, _Fields.METHOD, _Fields.DATA};
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.HEADERS, new org.apache.thrift.meta_data.FieldMetaData("headers", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP,
                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING),
                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
        tmpMap.put(_Fields.CONTROLLER, new org.apache.thrift.meta_data.FieldMetaData("controller", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.METHOD, new org.apache.thrift.meta_data.FieldMetaData("method", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.DATA, new org.apache.thrift.meta_data.FieldMetaData("data", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftInvokeRequest.class, metaDataMap);
    }

    public ThriftInvokeRequest() {
    }

    public ThriftInvokeRequest(
            java.util.Map<java.lang.String, java.lang.String> headers) {
        this();
        this.headers = headers;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ThriftInvokeRequest(ThriftInvokeRequest other) {
        if (other.isSetHeaders()) {
            java.util.Map<java.lang.String, java.lang.String> __this__headers = new java.util.HashMap<java.lang.String, java.lang.String>(other.headers);
            this.headers = __this__headers;
        }
        if (other.isSetController()) {
            this.controller = other.controller;
        }
        if (other.isSetMethod()) {
            this.method = other.method;
        }
        if (other.isSetData()) {
            this.data = other.data;
        }
    }

    public ThriftInvokeRequest deepCopy() {
        return new ThriftInvokeRequest(this);
    }

    @Override
    public void clear() {
        this.headers = null;
        this.controller = null;
        this.method = null;
        this.data = null;
    }

    public int getHeadersSize() {
        return (this.headers == null) ? 0 : this.headers.size();
    }

    public void putToHeaders(java.lang.String key, java.lang.String val) {
        if (this.headers == null) {
            this.headers = new java.util.HashMap<java.lang.String, java.lang.String>();
        }
        this.headers.put(key, val);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
        return this.headers;
    }

    public ThriftInvokeRequest setHeaders(@org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String, java.lang.String> headers) {
        this.headers = headers;
        return this;
    }

    public void unsetHeaders() {
        this.headers = null;
    }

    /** Returns true if field headers is set (has been assigned a value) and false otherwise */
    public boolean isSetHeaders() {
        return this.headers != null;
    }

    public void setHeadersIsSet(boolean value) {
        if (!value) {
            this.headers = null;
        }
    }

    /**
     * controller 就是java的类 注意这个 我们项目中间 controller 是需要取一个别名的
     */
    @org.apache.thrift.annotation.Nullable
    public java.lang.String getController() {
        return this.controller;
    }

    /**
     * controller 就是java的类 注意这个 我们项目中间 controller 是需要取一个别名的
     */
    public ThriftInvokeRequest setController(@org.apache.thrift.annotation.Nullable java.lang.String controller) {
        this.controller = controller;
        return this;
    }

    public void unsetController() {
        this.controller = null;
    }

    /** Returns true if field controller is set (has been assigned a value) and false otherwise */
    public boolean isSetController() {
        return this.controller != null;
    }

    public void setControllerIsSet(boolean value) {
        if (!value) {
            this.controller = null;
        }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.String getMethod() {
        return this.method;
    }

    public ThriftInvokeRequest setMethod(@org.apache.thrift.annotation.Nullable java.lang.String method) {
        this.method = method;
        return this;
    }

    public void unsetMethod() {
        this.method = null;
    }

    /** Returns true if field method is set (has been assigned a value) and false otherwise */
    public boolean isSetMethod() {
        return this.method != null;
    }

    public void setMethodIsSet(boolean value) {
        if (!value) {
            this.method = null;
        }
    }

    /**
     * data 注意这个地方 为了兼容多个参数。传递的是一个 json的数组
     * 全部都是数组 哪怕你调用的method 只有一个对象 也用数组包裹一下  Arrays.asList
     */
    @org.apache.thrift.annotation.Nullable
    public java.lang.String getData() {
        return this.data;
    }

    /**
     * data 注意这个地方 为了兼容多个参数。传递的是一个 json的数组
     * 全部都是数组 哪怕你调用的method 只有一个对象 也用数组包裹一下  Arrays.asList
     */
    public ThriftInvokeRequest setData(@org.apache.thrift.annotation.Nullable java.lang.String data) {
        this.data = data;
        return this;
    }

    public void unsetData() {
        this.data = null;
    }

    /** Returns true if field data is set (has been assigned a value) and false otherwise */
    public boolean isSetData() {
        return this.data != null;
    }

    public void setDataIsSet(boolean value) {
        if (!value) {
            this.data = null;
        }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
        switch (field) {
            case HEADERS:
                if (value == null) {
                    unsetHeaders();
                } else {
                    setHeaders((java.util.Map<java.lang.String, java.lang.String>) value);
                }
                break;

            case CONTROLLER:
                if (value == null) {
                    unsetController();
                } else {
                    setController((java.lang.String) value);
                }
                break;

            case METHOD:
                if (value == null) {
                    unsetMethod();
                } else {
                    setMethod((java.lang.String) value);
                }
                break;

            case DATA:
                if (value == null) {
                    unsetData();
                } else {
                    setData((java.lang.String) value);
                }
                break;

        }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.Object getFieldValue(_Fields field) {
        switch (field) {
            case HEADERS:
                return getHeaders();

            case CONTROLLER:
                return getController();

            case METHOD:
                return getMethod();

            case DATA:
                return getData();

        }
        throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new java.lang.IllegalArgumentException();
        }

        switch (field) {
            case HEADERS:
                return isSetHeaders();
            case CONTROLLER:
                return isSetController();
            case METHOD:
                return isSetMethod();
            case DATA:
                return isSetData();
        }
        throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
        if (that == null)
            return false;
        if (that instanceof ThriftInvokeRequest)
            return this.equals((ThriftInvokeRequest) that);
        return false;
    }

    public boolean equals(ThriftInvokeRequest that) {
        if (that == null)
            return false;
        if (this == that)
            return true;

        boolean this_present_headers = true && this.isSetHeaders();
        boolean that_present_headers = true && that.isSetHeaders();
        if (this_present_headers || that_present_headers) {
            if (!(this_present_headers && that_present_headers))
                return false;
            if (!this.headers.equals(that.headers))
                return false;
        }

        boolean this_present_controller = true && this.isSetController();
        boolean that_present_controller = true && that.isSetController();
        if (this_present_controller || that_present_controller) {
            if (!(this_present_controller && that_present_controller))
                return false;
            if (!this.controller.equals(that.controller))
                return false;
        }

        boolean this_present_method = true && this.isSetMethod();
        boolean that_present_method = true && that.isSetMethod();
        if (this_present_method || that_present_method) {
            if (!(this_present_method && that_present_method))
                return false;
            if (!this.method.equals(that.method))
                return false;
        }

        boolean this_present_data = true && this.isSetData();
        boolean that_present_data = true && that.isSetData();
        if (this_present_data || that_present_data) {
            if (!(this_present_data && that_present_data))
                return false;
            if (!this.data.equals(that.data))
                return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetHeaders()) ? 131071 : 524287);
        if (isSetHeaders())
            hashCode = hashCode * 8191 + headers.hashCode();

        hashCode = hashCode * 8191 + ((isSetController()) ? 131071 : 524287);
        if (isSetController())
            hashCode = hashCode * 8191 + controller.hashCode();

        hashCode = hashCode * 8191 + ((isSetMethod()) ? 131071 : 524287);
        if (isSetMethod())
            hashCode = hashCode * 8191 + method.hashCode();

        hashCode = hashCode * 8191 + ((isSetData()) ? 131071 : 524287);
        if (isSetData())
            hashCode = hashCode * 8191 + data.hashCode();

        return hashCode;
    }

    @Override
    public int compareTo(ThriftInvokeRequest other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = java.lang.Boolean.valueOf(isSetHeaders()).compareTo(other.isSetHeaders());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetHeaders()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.headers, other.headers);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.valueOf(isSetController()).compareTo(other.isSetController());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetController()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.controller, other.controller);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.valueOf(isSetMethod()).compareTo(other.isSetMethod());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetMethod()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.method, other.method);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.valueOf(isSetData()).compareTo(other.isSetData());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetData()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.data, other.data);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
        java.lang.StringBuilder sb = new java.lang.StringBuilder("ThriftInvokeRequest(");
        boolean first = true;

        sb.append("headers:");
        if (this.headers == null) {
            sb.append("null");
        } else {
            sb.append(this.headers);
        }
        first = false;
        if (isSetController()) {
            if (!first) sb.append(", ");
            sb.append("controller:");
            if (this.controller == null) {
                sb.append("null");
            } else {
                sb.append(this.controller);
            }
            first = false;
        }
        if (isSetMethod()) {
            if (!first) sb.append(", ");
            sb.append("method:");
            if (this.method == null) {
                sb.append("null");
            } else {
                sb.append(this.method);
            }
            first = false;
        }
        if (isSetData()) {
            if (!first) sb.append(", ");
            sb.append("data:");
            if (this.data == null) {
                sb.append("null");
            } else {
                sb.append(this.data);
            }
            first = false;
        }
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class ThriftInvokeRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        public ThriftInvokeRequestStandardScheme getScheme() {
            return new ThriftInvokeRequestStandardScheme();
        }
    }

    private static class ThriftInvokeRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<ThriftInvokeRequest> {

        public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftInvokeRequest struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // HEADERS
                        if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
                            {
                                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                                struct.headers = new java.util.HashMap<java.lang.String, java.lang.String>(2 * _map0.size);
                                @org.apache.thrift.annotation.Nullable java.lang.String _key1;
                                @org.apache.thrift.annotation.Nullable java.lang.String _val2;
                                for (int _i3 = 0; _i3 < _map0.size; ++_i3) {
                                    _key1 = iprot.readString();
                                    _val2 = iprot.readString();
                                    struct.headers.put(_key1, _val2);
                                }
                                iprot.readMapEnd();
                            }
                            struct.setHeadersIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // CONTROLLER
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.controller = iprot.readString();
                            struct.setControllerIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 3: // METHOD
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.method = iprot.readString();
                            struct.setMethodIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 4: // DATA
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.data = iprot.readString();
                            struct.setDataIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftInvokeRequest struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.headers != null) {
                oprot.writeFieldBegin(HEADERS_FIELD_DESC);
                {
                    oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.headers.size()));
                    for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter4 : struct.headers.entrySet()) {
                        oprot.writeString(_iter4.getKey());
                        oprot.writeString(_iter4.getValue());
                    }
                    oprot.writeMapEnd();
                }
                oprot.writeFieldEnd();
            }
            if (struct.controller != null) {
                if (struct.isSetController()) {
                    oprot.writeFieldBegin(CONTROLLER_FIELD_DESC);
                    oprot.writeString(struct.controller);
                    oprot.writeFieldEnd();
                }
            }
            if (struct.method != null) {
                if (struct.isSetMethod()) {
                    oprot.writeFieldBegin(METHOD_FIELD_DESC);
                    oprot.writeString(struct.method);
                    oprot.writeFieldEnd();
                }
            }
            if (struct.data != null) {
                if (struct.isSetData()) {
                    oprot.writeFieldBegin(DATA_FIELD_DESC);
                    oprot.writeString(struct.data);
                    oprot.writeFieldEnd();
                }
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class ThriftInvokeRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        public ThriftInvokeRequestTupleScheme getScheme() {
            return new ThriftInvokeRequestTupleScheme();
        }
    }

    private static class ThriftInvokeRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<ThriftInvokeRequest> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, ThriftInvokeRequest struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetHeaders()) {
                optionals.set(0);
            }
            if (struct.isSetController()) {
                optionals.set(1);
            }
            if (struct.isSetMethod()) {
                optionals.set(2);
            }
            if (struct.isSetData()) {
                optionals.set(3);
            }
            oprot.writeBitSet(optionals, 4);
            if (struct.isSetHeaders()) {
                {
                    oprot.writeI32(struct.headers.size());
                    for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter5 : struct.headers.entrySet()) {
                        oprot.writeString(_iter5.getKey());
                        oprot.writeString(_iter5.getValue());
                    }
                }
            }
            if (struct.isSetController()) {
                oprot.writeString(struct.controller);
            }
            if (struct.isSetMethod()) {
                oprot.writeString(struct.method);
            }
            if (struct.isSetData()) {
                oprot.writeString(struct.data);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, ThriftInvokeRequest struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(4);
            if (incoming.get(0)) {
                {
                    org.apache.thrift.protocol.TMap _map6 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
                    struct.headers = new java.util.HashMap<java.lang.String, java.lang.String>(2 * _map6.size);
                    @org.apache.thrift.annotation.Nullable java.lang.String _key7;
                    @org.apache.thrift.annotation.Nullable java.lang.String _val8;
                    for (int _i9 = 0; _i9 < _map6.size; ++_i9) {
                        _key7 = iprot.readString();
                        _val8 = iprot.readString();
                        struct.headers.put(_key7, _val8);
                    }
                }
                struct.setHeadersIsSet(true);
            }
            if (incoming.get(1)) {
                struct.controller = iprot.readString();
                struct.setControllerIsSet(true);
            }
            if (incoming.get(2)) {
                struct.method = iprot.readString();
                struct.setMethodIsSet(true);
            }
            if (incoming.get(3)) {
                struct.data = iprot.readString();
                struct.setDataIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

